languageCode = "en"
languageName = "English"
weight = 1

copyright = "Copy, _right?_ :thinking_face:"

[languages]
  [languages.en]
    [languages.en.params]
      isoCode = "en"
      displayName = "EN"
      rtl = false
      dateFormat = "2 January 2006"
      description = "Just my personal website where we talk about software development and other stuff."


[params.author]
name = "David Salazar"
image = "images/author.png"
headline = "Hi, here we talk about software development, Javascript, self-taught education and other stuff."
# bio = "I'm a self taught Software Developer"
links = [
  { email = "mailto:davidjsmorenodev@gmail.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  { github = "https://github.com/davidjsalazarmoreno" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  # { hashnode = "https://davidjsmoreno.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  { linkedin = "https://www.linkedin.com/in/david-salazar-63500724" },
  #   { mastodon = "https://mastodon.instance/@username" },
  { medium = "https://medium.com/@davidjsmoreno" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  # { twitter = "https://twitter.com/davidjsmoreno" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
]
